GET http://localhost:2424/todos/?status=TO%20DO

###

GET http://localhost:2424/todos/?status=IN%20PROGRESS

###

GET http://localhost:2424/todos/?priority=LOW&status=DONE

###
GET http://localhost:2424/todos/?search_q=Play

###
GET http://localhost:2424/todos/4/

###
POST http://localhost:2424/todos/
Content-Type: application/json

{
    "id" : 4,
    "todo" : "Play Volleyball",
    "priority" : "MEDIUM",
    "status" : "IN PROGRESS"
}

###
PUT http://localhost:2424/todos/2/
Content-Type: application/json

{
    "status" : "IN PROGRESS"
}

###
DELETE http://localhost:2424/todos/4/
